@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.toast.apocalypse.datagen.biomemodifier;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;