# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
# MAJOR, API, MINOR
mod_version=4.11.10
# b - Beta
# a - Alpha
# r - Release
mod_state=r
#
# MC
mc_version=1.20.1
forge_version=47.4.10
#
# crust-1.20.1-5.1.1
crust_api_version=8824405
crust_src_version=8824411
#
# JEI
jei_version=15.3.0.4
#
# Jade
jade_version=6855440
#
# RyoamicLights
ryoamic_version=5353333
ryoamic_src_version=5353334
obsidianui_version=5279713
#
# Serene Seasons
serene_s_version=4761603
#
# Special Mobs
sm_version=8014675
#
# Natural Absorption
na_version=7572073