@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.toast.apocalypse.datagen.advancement;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;