modLoader="javafml"
loaderVersion="[36,)"
license="Same license as FatherToast's project (none)"

[[mods]]
    modId="apocalypse"
    version="${file.jarVersion}"
    displayName="Apocalypse"
    logoFile="examplemod.png"
    credits="Sarinsa (Maintenance and porting)"
    authors="FatherToast (Original author)"
    description="The longer you stay in the world, the harder the monsters get. The full moon empowers monsters, the rain hurts you, and thunder causes mobs to end up in strange places. Good luck!"


[[dependencies.apocalypse]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apocalypse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
