modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/Sarinsa/Apocalypse-Rebooted/issues"

[[mods]]
    modId="apocalypse"
    version="${file.jarVersion}"
    displayName="Apocalypse Rebooted"
    updateJSONURL="https://raw.githubusercontent.com/Sarinsa/Apocalypse-Rebooted/1.19.X/version_check.json"
    logoFile="logo.png"
    credits="Sarinsa (Maintenance and porting), Frenderman (Artwork), Evo (Artwork), SoyTutta (Artwork)"
    authors="FatherToast (Original author and brainstormer)"
    description="The longer you stay in the world, the more powerful the monsters get. It may start raining acid, thunderstorms causes strange things to happen, and full moon nights empowers monsters and summons deadly foes that will do anything in their power to hunt you down. Good luck!"

[[dependencies.apocalypse]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.apocalypse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"

[modproperties.apocalypse]
    catalogueImageIcon="logo.png"
    configuredBackground="apocalypse:textures/gui/advancements/backgrounds/night_sky_bright.png"
