@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.toast.apocalypse.common.trap_actions;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;